apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebuka-deploy
spec:
  selector:
    matchLabels:
      app: ebuka-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: ebuka-deploy
    spec:
      containers:
        - name: profile
          image: dockerebuka101/mywebiste-app
          ports:
            - containerPort: 80
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ebuka-deploy
  labels:
    app: ebuka-deploy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: ebuka-deploy
  type: LoadBalancer
